# general exit codes
EXIT_CODE_FINAL_STATUS_SUCCESS = 0
EXIT_CODE_UNKNOWN_ERROR = 3
EXIT_CODE_INVALID_CREDENTIALS = 200
EXIT_CODE_BAD_REQUEST = 201

# trigger sync exit codes
EXIT_CODE_SYNC_REFRESH_ERROR = 202
EXIT_CODE_SYNC_ALREADY_RUNNING = 203
EXIT_CODE_SYNC_INVALID_SOURCE_ID = 204

# verify sync status exit codes
EXIT_CODE_FINAL_STATUS_INCOMPLETE = 210
EXIT_CODE_FINAL_STATUS_ERRORED = 211
EXIT_CODE_FINAL_STATUS_INVALID = 212
EXIT_CODE_UNKNOWN_STATUS = 213