EXIT_CODE_INVALID_CREDENTIALS = 200
EXIT_CODE_BAD_REQUEST = 201
EXIT_CODE_SYNC_REFRESH_ERROR = 210
EXIT_CODE_SYNC_ALREADY_RUNNING = 212
EXIT_CODE_SYNC_INVALID_SOURCE_ID = 213
EXIT_CODE_UNKNOWN_ERROR = 3